# Cls 0. python, numpy, matplotlib

## Introduction

Python is a great general-purpose programming language on its own, but with the help of a few popular
libraries (numpy, scipy, matplotlib) it becomes a powerful environment for scientific computing.

These exercises serve as a quick crash course both on the Python programming language and on the use
of Python for scientific computing.

In this lab you will practice:

* Basic Python: Basic data types (Containers, Lists, Dictionaries, Sets, Tuples), Functions, Classes
* Numpy: Arrays, Array indexing, Datatypes, Array math, Broadcasting
* Matplotlib: Plotting, Subplots, Images

## A Brief Note on Python Versions

As of Spring 2026, Google Colab uses Python 3.12 by default. You can check your Python version at the command line by running
`python --version`.

In [ ]:
!python --version

Python 3.12.13


## Basics of Python

Python is a high-level, dynamically typed multiparadigm programming language. Python code is often
said to be almost like pseudocode, since it allows you to express very powerful ideas in very few
lines of code while being very readable.

**Example 1.** Write a function `quicksort(arr)` that sorts a list of numbers using the classic quicksort algorithm:

* Return the list unchanged if it has one element or fewer (the base case).
* Otherwise pick the middle element (`arr[len(arr) // 2]`) as the pivot.
* Use three list comprehensions to split the list into the elements less than, equal to, and greater
  than the pivot.
* Recurse on the two outer partitions and concatenate the three pieces.

Call it on `[3, 6, 8, 10, 1, 2, 1]` and print the result. Expected output: `[1, 1, 2, 3, 6, 8, 10]`.

In [ ]:
def quicksort(arr):
    if len(arr) <= 1:
        return arr
    pivot = arr[len(arr) // 2]
    left = [x for x in arr if x < pivot]
    middle = [x for x in arr if x == pivot]
    right = [x for x in arr if x > pivot]
    return quicksort(left) + middle + quicksort(right)

print(quicksort([3,6,8,10,1,2,1]))

[1, 1, 2, 3, 6, 8, 10]


### Basic data types

#### Numbers

**Exercise 2.** Integers and floats work as you would expect from other languages.

* Assign the integer `3` to a variable `x`, then print both the value and its type using `type(x)`.
* Print the result of adding 1, subtracting 1, multiplying by 2, and raising to the power of 2
  (use the `**` operator for exponentiation).

In [7]:
# Your code here

x = 2
type(x)

int

In [8]:
x+1
x*2
x ** 2

4

**Exercise 3.** Python supports compound assignment operators.

* Increase `x` by 1 using `+=` and print it.
* Double `x` using `*=` and print it.

Note that unlike many languages, Python does *not* have unary increment (`x++`) or decrement (`x--`)
operators.

In [11]:
# Your code here

x += 1 # x = x + 1
x **= 2
x

289

**Exercise 4.** Now do the same with a floating point number.

* Assign `2.5` to a variable `y` and print its type.
* On one line, print `y`, `y + 1`, `y * 2` and `y ** 2`.

Python integers have arbitrary precision. Python also has a built-in type for complex numbers; you
can find all of the details in the
[documentation](https://docs.python.org/3/library/stdtypes.html#numeric-types-int-float-complex).

In [ ]:
# Your code here

#### Booleans

**Exercise 5.** Python implements all of the usual operators for Boolean logic, but uses English words rather than
symbols (`&&`, `||`, etc.).

* Use a single tuple-unpacking assignment to bind `t` to `True` and `f` to `False`, and print the type
  of `t`.
* Print, one per line: the logical AND of `t` and `f`, the logical OR, the negation of `t`, and the
  logical XOR of `t` and `f` (hint: `!=` behaves as XOR on booleans).

In [15]:
# Your code here
t, f = True, False
t, f

(True, False)

In [18]:
print(t and f)
print(t or f)
print(not t)
print(t ^ f)

False
True
False
True


#### Strings

**Exercise 6.** * Create a variable `hello` holding the string `hello` using single quotes, and a variable `world`
  holding `world` using double quotes — Python does not care which you use.
* Print `hello` together with its length (`len`).

In [19]:
# Your code here
hello = "hello"
world = 'world'

**Exercise 7.** Build a new string `hw` by concatenating `hello`, a single space, and `world` with the `+` operator,
then print it. Expected output: `hello world`.

In [21]:
# Your code here
hello + ' ' + world

'hello world'

**Exercise 8.** Build a string `hw12` that reads `hello world 12` using an f-string that interpolates `hello`,
`world` and the number `12`, then print it.

Python 3.6+ introduced **f-strings** (formatted string literals), which are the preferred way to
format strings. You may also see the older `.format()` method in existing code:

```python
hw12 = '{} {} {}'.format(hello, world, 12)  # older style, still works
```

In [22]:
# Your code here
f"{hello} {world} {1234+1234}"

'hello world 2468'

**Exercise 9.** String objects have a bunch of useful methods. Assign `"hello"` to `s`, then print the result of
each of the following, one per line:

* capitalizing the string
* converting it to uppercase (prints `HELLO`)
* right-justifying it in a field of width 7, padded with spaces
* centering it in a field of width 7, padded with spaces
* replacing every `l` with `(ell)`
* stripping leading and trailing whitespace from the separate literal `'  world '`

You can find a list of all string methods in the
[documentation](https://docs.python.org/3/library/stdtypes.html#string-methods).

In [26]:
# Your code here
'     wordl     '.lstrip().lower()

'wordl     '

### Containers

Python includes several built-in container types: lists, dictionaries, sets, and tuples.

#### Lists

**Exercise 10.** A list is the Python equivalent of an array, but is resizeable and can contain elements of different
types.

* Create a list `xs` containing `3, 1, 2`. Print the whole list along with the element at index 2.
* Print the last element using a negative index (negative indices count from the end; prints `2`).

In [ ]:
# Your code here
xs = [3, 1, 2] # mutable 
xs[0] = 5
xs

[5, 1, 2]

**Exercise 11.** Keep working with the same list `xs`:

* Assign the string `'foo'` to index 2 to show that lists can hold elements of different types, then
  print the list.
* Append `'bar'` to the end of the list with `append`, then print the list.
* Remove and return the last element with `pop`, storing it in `x`, then print both `x` and `xs`.

As usual, you can find all the gory details about lists in the
[documentation](https://docs.python.org/3/tutorial/datastructures.html#more-on-lists).

In [35]:
# Your code here

xs.append("asdf")
xs

[5, 1, 2, 'asdf', 'asdf', 'asdf', 'asdf', 'asdf']

#### Slicing

**Exercise 12.** In addition to accessing list elements one at a time, Python provides concise syntax to access
sublists; this is known as slicing. Create `nums = list(range(5))` (`range` generates a sequence of
integers, `list()` converts it to a list) and print each of the following:

* the whole list — `[0, 1, 2, 3, 4]`
* a slice from index 2 up to (but excluding) index 4 — `[2, 3]`
* a slice from index 2 to the end — `[2, 3, 4]`
* a slice from the start up to index 2 — `[0, 1]`
* a slice of the whole list using `[:]` — `[0, 1, 2, 3, 4]`
* a slice that omits the last element using a negative index — `[0, 1, 2, 3]`

Finally, assign the sublist `[8, 9]` to the slice `nums[2:4]` and print `nums`. Expected output:
`[0, 1, 8, 9, 4]`.

In [39]:
# Your code here

nums = list(range(5))
# nums[start : end : step]
nums[::2]
nums[1::2]
nums[::-1]

[4, 3, 2, 1, 0]

#### Loops

**Exercise 13.** Create the list `animals = ['cat', 'dog', 'monkey']` and use a `for` loop to print each element on
its own line.

In [40]:
# Your code here

for a in ['cat', 'dog', 'monkey']:
    print(a)

cat
dog
monkey


**Exercise 14.** You often want access to the index of each element within the body of a loop. Loop over the same
`animals` list with the built-in `enumerate` function and print a numbered line per animal using an
f-string, so the output is:

```
#1: cat
#2: dog
#3: monkey
```

In [42]:
animals = ['cat', 'dog', 'monkey']

for i, an in enumerate(animals):
    print(i, an)

0 cat
1 dog
2 monkey


#### List comprehensions

**Exercise 15.** When programming, frequently we want to transform one type of data into another.

* Given `nums = [0, 1, 2, 3, 4]`, compute the list of squares using an explicit `for` loop that
  appends to an initially empty list, and print it.
* Then rewrite the same computation as a one-line list comprehension and print the result.

Both should print `[0, 1, 4, 9, 16]`.

In [46]:
# Your code here

nums = [0, 1, 2, 3, 4]
squares = [n ** 2 for n in nums]
squares

[0, 1, 4, 9, 16]

**Exercise 16.** List comprehensions can also contain conditions. Using `nums = [0, 1, 2, 3, 4]`, write a single list
comprehension that squares only the even numbers, and print it. Expected output: `[0, 4, 16]`.

In [48]:
# Your code here
squares = [n ** 2 for n in nums if n % 2 == 1]
squares

[1, 9]

#### Dictionaries

**Exercise 17.** A dictionary stores (key, value) pairs, similar to a `Map` in Java or an object in Javascript.

* Create a dictionary `d` mapping `'cat'` to `'cute'` and `'dog'` to `'furry'`.
* Print the entry for `'cat'` (prints `cute`).
* Print whether `'cat'` is a key of the dictionary using the `in` operator (prints `True`).
* Add the entry `'fish' -> 'wet'` and print it back out.

In [59]:
# Your code here

d = {}
d["key"] = 234
d

{'key': 234}

In [62]:
d.update({"key1": 2321})
d

{'key': 234, 'key1': 2321}

**Exercise 18.** Show that looking up a key that is not in the dictionary raises an error: print `d['monkey']`.

**This cell is expected to fail** with `KeyError: 'monkey'` — run it, read the traceback, then move
on.

In [ ]:
# Your code here

**Exercise 19.** Instead of failing, you can supply a default.

* Use `d.get` with the default `'N/A'` to look up `'monkey'` (prints `N/A`) and `'fish'`
  (prints `wet`).
* Delete the `'fish'` entry with `del`, then use `d.get('fish', 'N/A')` again to confirm the key is
  gone.

You can find all you need to know about dictionaries in the
[documentation](https://docs.python.org/3/library/stdtypes.html#dict).

In [ ]:
# Your code here

**Exercise 20.** It is easy to iterate over the key-value pairs in a dictionary. Create
`d = {'person': 2, 'cat': 4, 'spider': 8}` and loop over `d.items()` to print a line per entry in the
form `A person has 2 legs`.

In [68]:
# Your code here

for key, value in d.items():
    print(key, value)

key 234
key1 2321


**Exercise 21.** Dictionary comprehensions are similar to list comprehensions, but let you construct dictionaries.
Given `nums = [0, 1, 2, 3, 4]`, build a dictionary mapping each even number to its square and print
it. Expected output: `{0: 0, 2: 4, 4: 16}`.

In [69]:
# Your code here

{f"key{i}": i for i in range(5)}

{'key0': 0, 'key1': 1, 'key2': 2, 'key3': 3, 'key4': 4}

#### Sets

**Exercise 22.** A set is an unordered collection of distinct elements.

* Create the set `animals = {'cat', 'dog'}` and print whether `'cat'` and `'fish'` are members
  (`True` then `False`).
* Add `'fish'` to the set, then print its membership again along with the number of elements in the
  set.
* Add `'cat'` a second time and print the length to show that adding an element already in the set
  does nothing; then `remove` `'cat'` and print the length again.

In [74]:
# Your code here
animals = {'cat', 'dog'}

print('fish' in animals)

animals.add('fish')
animals.add('fish')
animals


False


{'cat', 'dog', 'fish'}

**Exercise 23.** Iterating over a set has the same syntax as iterating over a list; however, since sets are unordered,
you cannot make assumptions about the order in which you visit the elements.

Create `animals = {'cat', 'dog', 'fish'}` and print a numbered line per element using `enumerate`,
as you did for the list.

In [ ]:
# Your code here



**Exercise 24.** Like lists and dictionaries, we can construct sets using set comprehensions. Import `sqrt` from the
`math` module and print the set of integer square roots `int(sqrt(x))` for every `x` in `range(30)`.

In [78]:
# Your code here

set(x ** 2 for x in range(3))

{0, 1, 4}

#### Tuples

**Exercise 25.** A tuple is an (immutable) ordered list of values. A tuple is in many ways similar to a list; one of
the most important differences is that tuples can be used as keys in dictionaries and as elements of
sets, while lists cannot.

* Use a dictionary comprehension to build `d` whose keys are the tuples `(x, x + 1)` and whose values
  are `x`, for `x` in `range(10)`.
* Create the tuple `t = (5, 6)` and print its type.
* Print `d[t]` and `d[(1, 2)]`.

In [80]:
# Your code here

d[(1, 2)] = "asdf"
d

{'key': 234, 'key1': 2321, (1, 2): 'asdf'}

**Exercise 26.** Show that tuples are immutable: try to assign `1` to `t[0]`.

**This cell is expected to fail** with a `TypeError` — run it, read the message, then move on.

In [81]:
# Your code here
t = (5, 6)
t[0] = 2


TypeError: 'tuple' object does not support item assignment

### Functions

**Exercise 27.** Python functions are defined using the `def` keyword. Write a function `sign(x)` that returns the
string `'positive'`, `'negative'` or `'zero'` depending on the sign of `x` (use `if` / `elif` /
`else`). Then loop over `[-1, 0, 1]` and print `sign(x)` for each value.

In [82]:
# Your code here

def sign(x):
    return "positive" if x >= 0 else "negative"

In [83]:
sign(-3)

'negative'

**Exercise 28.** We will often define functions that take optional keyword arguments. Write a function
`hello(name, loud=False)` that:

* prints `HELLO, <NAME>` with the name uppercased when `loud` is true, and
* prints `Hello, <name>!` otherwise.

Call it as `hello('Bob')` and as `hello('Fred', loud=True)`.

In [86]:
# Your code here
def hello(name, loud=False):
    print(f"Hello {name}" if not loud else f"Hello {name}".upper())

hello("Name")
hello("Name", True)

Hello Name
HELLO NAME


### Classes

**Exercise 29.** The syntax for defining classes in Python is straightforward. Define a class `Greeter` that:

* takes a `name` in its constructor (`__init__`) and stores it as an instance variable `self.name`;
* has an instance method `greet(self, loud=False)` that prints `HELLO, <NAME>` when `loud` is true and
  `Hello, <name>!` otherwise.

Construct an instance with the name `'Fred'`, then call `greet()` and `greet(loud=True)` on it.

In [ ]:
# Your code here

## Numpy

Numpy is the core library for scientific computing in Python. It provides a high-performance
multidimensional array object, and tools for working with these arrays.
To use Numpy, we first need to import the `numpy` package:

In [87]:
import numpy as np

### Arrays

A numpy array is a grid of values, all of the same type, and is indexed by a tuple of nonnegative
integers. The number of dimensions is the `ndim` of the array; the `shape` of an array is a tuple of
integers giving the size of the array along each dimension.

**Exercise 30.** We can initialize numpy arrays from nested Python lists, and access elements using square brackets.

* Create a 1D array `a` from the list `[1, 2, 3]`.
* Print its `type`, its `shape`, and its three elements.
* Change the element at index 0 to `5` and print the array.

In [92]:
# Your code here

a = np.array([1, 2, 3])
a.shape

(3,)

**Exercise 31.**  Create a 2D array `b` from the nested list `[[1, 2, 3], [4, 5, 6]]` and print it.
* Print its `shape` (expected `(2, 3)`), then print the elements at positions `[0, 0]`, `[0, 1]` and
  `[1, 0]`.

In [101]:
# Your code here
b = np.array([[1, 2, 3], [4, 5, 6]])
print(b.shape)
print(type(b))

print(b)

b[0, 0], b[0, 1], b[1, 0]

(2, 3)
<class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]]


(np.int64(1), np.int64(2), np.int64(4))

**Exercise 32.** Numpy also provides many functions to create arrays. Create and print each of the following:

* `a` — a 2x2 array of all zeros
* `b` — a 1x2 array of all ones
* `c` — a 2x2 constant array filled with the value `7`
* `d` — a 2x2 identity matrix

In [115]:
# Your code here

a = np.zeros(shape=(2, 2))
print(a)

b = np.ones(shape=(1, 2))
print(b)

# c = np.full(shape=(2, 2), fill_value=7)
c = np.ones(shape=(2, 2)) * 7
print(c)

[[0. 0.]
 [0. 0.]]
[[1. 1.]]
[[7. 7.]
 [7. 7.]]


**Exercise 33.** Create a random number generator with `np.random.default_rng()`, use it to build a 2x2 array `e`
filled with random values drawn from `[0, 1)`, and print it.

In [120]:
# Your code here

rng = np.random.default_rng()

e = rng.uniform(size=(2, 2))
e

array([[0.10828137, 0.42956204],
       [0.11282145, 0.02848585]])

In this course you will frequently work with arrays that have more than two dimensions —
for example, a color image has shape `(height, width, channels)` and a batch of images has shape
`(num_images, height, width, channels)`. The `axis` parameter in NumPy functions specifies which
dimension to operate along.

**Exercise 34.** Create a 3D array `a` of ones with shape `(2, 3, 4)`. Print its shape, then print the *shape* of the
result of summing it:

* over axis 0 — expected `(3, 4)`
* over axis 2 — expected `(2, 3)`
* over both axes 0 and 2 at once, by passing a tuple as `axis` — expected `(3,)`

In [129]:
# Your code here

a = np.ones(shape=(2, 3, 4))
# print(a)
print(a.sum(axis=0).shape)
print(a.sum(axis=1).shape)
print(a.sum(axis=2).shape)

(3, 4)
(2, 4)
(2, 3)


### Array indexing

Numpy offers several ways to index into arrays.

**Exercise 35.** Slicing works similarly to Python lists. Since arrays may be multidimensional, you must specify a
slice for each dimension of the array.

* Create the 2D array `a` of shape `(3, 4)` holding the values 1 through 12 in row-major order.
* Use a single slicing expression to pull out `b`, the subarray consisting of the first 2 rows and
  columns 1 and 2, then print it. Expected output:

```
[[2 3]
 [6 7]]
```

In [135]:
# Your code here

a = np.arange(12).reshape((3, 4)) + 1
b = a[0:2, 1:3]
b

array([[2, 3],
       [6, 7]])

**Exercise 36.** A slice of an array is a **view** into the same data, so modifying it modifies the original array.
This is a common source of bugs — if you need an independent copy, use `.copy()`.

Print `a[0, 1]`, then assign `77` to `b[0, 0]`, then print `a[0, 1]` again to show that the two
expressions refer to the same piece of data.

In [137]:
# Your code here
b[0, 0] = 77
a

array([[ 1, 77,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

**Exercise 37.** You can also mix integer indexing with slice indexing. However, doing so yields an array of lower
dimensionality than the original array. Note that this is quite different from the way MATLAB handles
array slicing.

Re-create the `(3, 4)` array `a` holding 1 through 12 (the previous exercise modified it) and print it.

In [143]:
# Your code here
a = np.arange(12).reshape((3, 4)) + 1
a[0, 1:3][None, :].shape

(1, 2)

**Exercise 38.** Access the middle row of `a` in three ways and print each result together with its shape:

* `a[1, :]` — mixing an integer with a slice, giving a 1D view of the second row
* `a[1:2, :]` — using only slices, giving a 2D view of the second row
* `a[[1], :]` — using a list index, also giving a 2D view

Mixing integer indexing with slices yields an array of fewer dimensions, while using only slices
yields an array of the same dimensionality as the original.

In [ ]:
# Your code here

**Exercise 39.** Make the same distinction when accessing *columns* of `a`: print `a[:, 1]` and `a[:, 1:2]`, each with
its shape, and note how the shapes differ.

In [146]:
# Your code here
a[0:1, 1:3]

array([[2, 3]])

**Exercise 40.** Integer array indexing: when you index into numpy arrays using slicing, the resulting array view will
always be a subarray of the original array. In contrast, integer array indexing allows you to
construct arbitrary arrays using the data from another array.

* Create `a = np.array([[1, 2], [3, 4], [5, 6]])`.
* Using integer array indexing with the row indices `[0, 1, 2]` and column indices `[0, 1, 0]`, print
  the resulting array of shape `(3,)`.
* Print the equivalent array built by hand from the three individual elements `a[0, 0]`, `a[1, 1]` and
  `a[2, 0]` to confirm the two agree.

In [150]:
# Your code here

a = np.array([[1, 2], [3, 4], [5, 6]])
print(a)
b = a[[0, 1, 2], [0, 1, 0]]
print(b)

[[1 2]
 [3 4]
 [5 6]]
[1 4 5]


**Exercise 41.** When using integer array indexing you can reuse the same element from the source array.

* Print the result of indexing `a` with row indices `[0, 0]` and column indices `[1, 1]`.
* Print the equivalent array built by hand from `a[0, 1]` twice.

In [ ]:
# Your code here

**Exercise 42.** One useful trick with integer array indexing is selecting or mutating one element from each row of a
matrix. Create `a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])` and print it.

In [151]:
# Your code here
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])

**Exercise 43.** * Create an index array `b = np.array([0, 2, 0, 1])`, one column index per row of `a`.
* Use `np.arange` together with `b` to select one element from each row of `a` and print the result.
  Expected output: `[ 1  6  7 11]`.

In [154]:
# Your code here

a.shape
b = np.array([0, 2, 0, 1])
a[np.arange(4), b]

array([ 1,  6,  7, 11])

**Exercise 44.** Using the same `np.arange`/`b` index pair, add `10` in place to the selected element of each row of
`a`, then print `a`.

In [ ]:
# Your code here

**Exercise 45.** Boolean array indexing lets you pick out arbitrary elements of an array. Frequently this type of
indexing is used to select the elements of an array that satisfy some condition.

* Create `a = np.array([[1, 2], [3, 4], [5, 6]])`.
* Build `bool_idx`, the boolean array of the same shape as `a` telling whether each element is
  greater than 2, and print it.

In [ ]:
# Your code here

**Exercise 46.** * Use `bool_idx` to index `a`, producing a 1D array of the elements corresponding to the `True`
  entries, and print it.
* Print the same result written as a single concise statement, without the intermediate variable.

For brevity we have left out a lot of details about numpy array indexing; if you want to know more you
should read the [documentation](https://numpy.org/doc/stable/user/basics.indexing.html).

In [160]:
# Your code here

a[a.sum(axis=1) % 2 == 0, :]

array([[1, 2, 3],
       [7, 8, 9]])

### Datatypes

Every numpy array is a grid of elements of the same type. Numpy provides a large set of numeric
datatypes that you can use to construct arrays. Numpy tries to guess a datatype when you create an
array, but functions that construct arrays usually also include an optional argument to explicitly
specify the datatype.

**Exercise 47.** * Create `x` from `[1, 2]` and `y` from `[1.0, 2.0]`, letting numpy choose the datatype in both cases.
* Create `z` from `[1, 2]` forcing the datatype to `np.int64`.
* Print the `dtype` of all three. Note how numpy inferred an integer type for `x` and a float type
  for `y`.

You can read all about numpy datatypes in the
[documentation](https://numpy.org/doc/stable/reference/arrays.dtypes.html).

In [161]:
# Your code here

np.int64
np.int32
np.int16

np.bool, np.str_, np.object_

(numpy.bool, numpy.str_, numpy.object_)

### Array math

**Exercise 48.** Basic mathematical functions operate elementwise on arrays, and are available both as operator
overloads and as functions in the numpy module.

Create `x = np.array([[1, 2], [3, 4]])` and `y = np.array([[5, 6], [7, 8]])`, both with
`dtype=np.float64`. Then print each of the following twice — once using the operator and once using
the equivalent numpy function (`np.add`, `np.subtract`, `np.multiply`, `np.divide`) — verifying the
two forms agree:

* the elementwise sum
* the elementwise difference
* the elementwise product
* the elementwise quotient

Finally print the elementwise square root of `x` using `np.sqrt`. Expected output:

```
[[ 1.          1.41421356]
 [ 1.73205081  2.        ]]
```

In [165]:
# Your code here
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])

print(x+y)
print(x-y)
print(x*y)
print(x/y)

[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [166]:
y[0, 0] = 0
print(x / y)

[[       inf 0.33333333]
 [0.42857143 0.5       ]]


/var/folders/18/f0_nd2f14c937fnzhrpz6r8c0000gp/T/ipykernel_2862/1958870292.py:2: RuntimeWarning: divide by zero encountered in divide
  print(x / y)


**Exercise 49.** Note that unlike MATLAB, `*` is elementwise multiplication, not matrix multiplication. We instead use
the `@` operator to compute inner products of vectors, to multiply a vector by a matrix, and to
multiply matrices.

Create the integer arrays `x = np.array([[1, 2], [3, 4]])`, `y = np.array([[5, 6], [7, 8]])`,
`v = np.array([9, 10])` and `w = np.array([11, 12])`, then print the inner product of `v` and `w`
using `@`. Expected output: `219`.

In [171]:
# Your code here
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])
print(x @ y)

v = np.array([9, 10])
w = np.array([11, 12])

print(v @ w)


[[19 22]
 [43 50]]
219


**Exercise 50.** The `@` operator is the standard way to do matrix multiplication in Python. You may also see
`np.dot()` and `v.dot(w)` in older code, which are equivalent for these operations. Print the inner
product of `v` and `w` again, once with the `v.dot(w)` method form and once with `np.dot(v, w)`.

In [ ]:
# Your code here

**Exercise 51.** Print the matrix / vector product of `x` and `v`, both with `@` and with `np.dot`. Both should produce
the 1D array `[29 67]`.

In [ ]:
# Your code here

**Exercise 52.** Print the matrix / matrix product of `x` and `y`, both with `@` and with `np.dot`. Both should produce
the 2D array:

```
[[19 22]
 [43 50]]
```

In [ ]:
# Your code here

**Exercise 53.** Numpy provides many useful functions for performing computations on arrays; one of the most useful is
`sum`. With `x = np.array([[1, 2], [3, 4]])`, print:

* the sum of all elements — `10`
* the sum of each column, by summing over axis 0 — `[4 6]`
* the sum of each row, by summing over axis 1 — `[3 7]`

In [ ]:
# Your code here

**Exercise 54.** Several other NumPy functions come up frequently in deep learning. Create
`x = np.array([[1, -2, 3], [-4, 5, -6]])` and print:

* the maximum along each row — `[3 5]`
* the *index* of the maximum in each row, using `argmax` — `[2 1]`
* `x` with its values clipped to the range `[-3, 3]`
* the ReLU of `x` — keep the positive values and zero out the rest, using `np.where`

Then, with `scores = np.array([2.0, 1.0, 0.1])`:

* compute the softmax of `scores` by exponentiating with `np.exp` and dividing by the sum of the
  exponentials, and print it (this pattern is the basis of cross-entropy loss)
* print the L2 norm of `scores` using `np.linalg.norm` (used in gradient checking and
  regularization)

You can find the full list of mathematical functions provided by numpy in the
[documentation](https://numpy.org/doc/stable/reference/routines.math.html).

In [181]:
# Your code here

x = np.array([[1, -2, 3], [-4, 5, -6]])
print(x)
print(x.shape)
print(x.max(axis=1))
print(x.argmax(axis=1))
print(x.clip(-3, 3))

[[ 1 -2  3]
 [-4  5 -6]]
(2, 3)
[3 5]
[2 1]
[[ 1 -2  3]
 [-3  3 -3]]


In [ ]:
np.where(x < 0)
x[np.where(x < 0)] = 0
x

array([[1, 0, 3],
       [0, 5, 0]])

In [189]:
# softmax (softargmax)
# (x1, x2, ..., xn) -> (e^x1 / (sum e^xi), ... , e^xn / (sum e^xi))

scores = np.array([2.0, 1.0, 0.1])
np.exp(scores) / np.exp(scores).sum() 

array([0.65900114, 0.24243297, 0.09856589])

**Exercise 55.** Apart from computing mathematical functions using arrays, we frequently need to reshape or otherwise
manipulate data in arrays. The simplest example is transposing a matrix, using the `T` attribute of
an array object.

* Print `x = np.array([[1, 2], [3, 4]])` and its transpose.
* Print the row vector `v = np.array([[1, 2, 3]])` (note the nested brackets — shape `(1, 3)`) and its
  transpose, which is a column vector of shape `(3, 1)`.

In [195]:
# Your code here

x = np.array([[1, 2], [3, 4]])

In [199]:
v = np.array([[1, 2, 3]])
v.shape
v.T.shape

(3, 1)

In [207]:
v = np.array([1, 2, 3])

v[None, :].T.shape

(3, 1)

**Exercise 56.** Another very common operation is `reshape`, which changes the shape of an array without changing its
data. You will use this constantly — for example, flattening an image into a vector, or reshaping
weight matrices.

Create `x = np.array([[1, 2, 3], [4, 5, 6]])` and print its original shape, then print:

* `x` flattened to a 1D vector with `reshape(-1)` (where `-1` means "infer this dimension")
* `x` flattened with `flatten()`, which is equivalent but always returns a copy
* `x` reshaped to a column vector of shape `(6, 1)`
* `x` reshaped to shape `(3, 2)`

In [210]:
# Your code here

np.arange(12).reshape((3, 4)).flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [212]:
a = np.arange(24).reshape((2, 3, 4))
a.shape

(2, 3, 4)

In [214]:
at = np.transpose(a, axes=(0, 2, 1))
at.shape

(2, 4, 3)

In [217]:
at[:, 1, :]

array([[ 1,  5,  9],
       [13, 17, 21]])

In [ ]:
# (B, H, W, C)
# axes = (0, 2, 1, 3) 


### Broadcasting

Broadcasting is a powerful mechanism that allows numpy to work with arrays of different shapes when
performing arithmetic operations. Frequently we have a smaller array and a larger array, and we want
to use the smaller array multiple times to perform some operation on the larger array.

**Exercise 57.** Suppose we want to add a constant vector to each row of a matrix. Start with the slow, explicit
version.

* Create `x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])` and `v = np.array([1, 0, 1])`.
* Create an uninitialized output matrix `y` with the same shape as `x` using `np.empty_like`.
* Write an explicit `for` loop over the four rows that adds `v` to each row of `x`, storing the result
  in `y`, then print `y`.

In [ ]:
# Your code here

**Exercise 58.** This works; however, when the matrix `x` is very large, computing an explicit loop in Python could be
slow. Note that adding the vector `v` to each row of the matrix `x` is equivalent to forming a matrix
`vv` by stacking multiple copies of `v` vertically, then performing elementwise summation of `x` and
`vv`.

Use `np.tile` to stack 4 copies of `v` on top of each other into `vv` and print it. Expected output:

```
[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]
```

In [ ]:
# Your code here

**Exercise 59.** Add `x` and `vv` elementwise into `y` and print it — the same result as the loop version.

In [ ]:
# Your code here

**Exercise 60.** Numpy broadcasting lets us perform this computation without actually creating multiple copies of `v`.
Re-create `x` and `v`, then add `v` to each row of `x` in a single expression `y = x + v`, and print
`y`.

In [ ]:
# Your code here

The line `y = x + v` works even though `x` has shape `(4, 3)` and `v` has shape `(3,)` due to
broadcasting; this line works as if `v` actually had shape `(4, 3)`, where each row was a copy of `v`,
and the sum was performed elementwise.

Broadcasting two arrays together follows these rules:

1. If the arrays do not have the same number of dimensions, prepend the shape of the lower-dimensional
   array with 1s until both shapes have the same length.
2. The two arrays are said to be compatible in a dimension if they have the same size in the
   dimension, or if one of the arrays has size 1 in that dimension.
3. The arrays can be broadcast together if they are compatible in all dimensions.
4. After broadcasting, each array behaves as if it had shape equal to the elementwise maximum of
   shapes of the two input arrays.
5. In any dimension where one array had size 1 and the other array had size greater than 1, the first
   array behaves as if it were copied along that dimension.

If this explanation does not make sense, try reading the
[broadcasting documentation](https://numpy.org/doc/stable/user/basics.broadcasting.html).

Functions that support broadcasting are known as universal functions. You can find the list of all
universal functions in the
[documentation](https://numpy.org/doc/stable/reference/ufuncs.html#available-ufuncs).

**Exercise 61.** Build an interactive widget that lets you experiment with broadcasting.

* Import `interact_manual`, `IntSlider` and `Layout` from `ipywidgets`.
* Write a function `explore_broadcasting(a_rows=4, a_cols=3, b_rows=1, b_cols=3)` that forms the two
  shapes `(a_rows, a_cols)` and `(b_rows, b_cols)`, creates arrays of ones with those shapes, and
  tries to add them inside a `try` / `except ValueError` block.
  * On success: print both input shapes and the result shape with a "broadcast succeeded" marker, then
    loop over the two dimensions and report which rule applied — the sizes are equal, A was stretched
    (its size was 1), or B was stretched.
  * On failure: print both shapes and the `ValueError` message.
* Wire the function up with `interact_manual`, giving each of the four arguments an `IntSlider` with
  `min=1`, `max=5`, the default value from the signature, and a readable description. Pass
  `layout=Layout(width="200px")` to keep the sliders compact.

Then use the widget to find shape pairs that broadcast and pairs that do not.

In [ ]:
# Your code here

Here are some applications of broadcasting:

**Exercise 62.** Compute the outer product of two vectors. With `v = np.array([1, 2, 3])` (shape `(3,)`) and
`w = np.array([4, 5])` (shape `(2,)`): reshape `v` into a column vector of shape `(3, 1)`, multiply it
by `w`, and print the resulting `(3, 2)` outer product.

In [ ]:
# Your code here

**Exercise 63.** Add a vector to each row of a matrix. With `x = np.array([[1, 2, 3], [4, 5, 6]])` of shape `(2, 3)`
and `v` of shape `(3,)`, print `x + v` — the shapes broadcast to `(2, 3)`.

In [ ]:
# Your code here

**Exercise 64.** Add a vector to each *column* of a matrix. `x` has shape `(2, 3)` and `w` has shape `(2,)`, so they do
not broadcast directly.

* Transpose `x` to shape `(3, 2)` so it can be broadcast against `w`, add `w`, and transpose the
  result back to shape `(2, 3)`. Print it.
* Then do the same thing a second way: reshape `w` into a column vector of shape `(2, 1)` and
  broadcast it directly against `x`. Print it and confirm the two results match.

In [ ]:
# Your code here

**Exercise 65.** Multiply a matrix by a constant. Numpy treats scalars as arrays of shape `()`, so they broadcast
against any shape. Print `x * 2`.

Broadcasting typically makes your code more concise and faster, so you should strive to use it where
possible.

In [ ]:
# Your code here

### Vectorization

A key skill for this course is **replacing Python loops with vectorized NumPy operations**.
NumPy operations run in optimized C under the hood, so they can be orders of magnitude faster than
equivalent Python loops. Whenever you find yourself writing a `for` loop over array elements, ask
whether you can express it with array operations instead.

**Exercise 66.** Measure the difference for yourself by building a benchmark widget.

* Import `interact_manual` and `IntSlider` from `ipywidgets`, and `time`.
* Write a function `benchmark_vectorization(size=500)` that:
  * builds a `(size, size)` array of standard normal values using
    `np.random.default_rng(0).standard_normal`;
  * computes the ReLU with a doubly-nested Python loop over every element, timing it with
    `time.time()`;
  * computes the same ReLU in one vectorized call to `np.maximum`, timing that too;
  * prints the array size and element count, both timings, and the speedup factor;
  * prints a two-line bar chart made of `█` characters comparing the two timings visually, scaling the
    vectorized bar relative to a 40-character loop bar.
* Wire it up with `interact_manual` and an `IntSlider` for `size` with `min=100`, `max=2000`,
  `step=100`, `value=500`.

Try a few sizes and note how the speedup grows.

In [ ]:
# Your code here

### Images as NumPy Arrays

In computer vision, images are just NumPy arrays. A color image is a 3D array of shape `(H, W, 3)`
(height, width, RGB channels), and a batch of images is a 4D array of shape `(N, H, W, 3)`.
Understanding shapes and axes is essential for the assignments.

**Exercise 67.** Simulate a batch of 16 RGB images, each 32x32 pixels, using
`np.random.default_rng(42).integers(0, 256, size=..., dtype=np.uint8)`. Then print:

* the shape of the batch, in `(N, H, W, C)` order
* the shape of a single image from the batch — `(H, W, C)`
* the shape of the red channel of the first image — `(H, W)`
* the mean pixel value per channel across the whole batch, by averaging over the N, H and W axes at
  once (pass a tuple as `axis`) — this should leave you with 3 numbers

This brief overview has touched on many of the important things that you need to know about numpy, but
is far from complete. Check out the [numpy reference](https://numpy.org/doc/stable/reference/) to find
out much more about numpy.

In [ ]:
# Your code here

## Matplotlib

Matplotlib is a plotting library. In this section you will practice with the `matplotlib.pyplot`
module, which provides a plotting system similar to that of MATLAB.

In [ ]:
import matplotlib.pyplot as plt

In modern versions of Colab and Jupyter, matplotlib plots are displayed inline by default, so no
special setup is needed.

### Plotting

**Exercise 68.** The most important function in `matplotlib` is `plot`, which allows you to plot 2D data.

* Build the x coordinates with `np.arange` from 0 to `3 * np.pi` in steps of `0.1`, and the y
  coordinates as the sine of x.
* Plot the points with `plt.plot`.

In [ ]:
# Your code here

**Exercise 69.** With just a little bit of extra work we can plot multiple lines at once and annotate the figure. Using
the same `x` as above:

* compute `y_sin` and `y_cos` as the sine and cosine of `x`;
* plot both curves on the same axes;
* label the x axis `x axis label` and the y axis `y axis label`;
* set the title to `Sine and Cosine`;
* add a legend labelling the two curves `Sine` and `Cosine`.

In [ ]:
# Your code here

### Subplots

**Exercise 70.** You can plot different things in the same figure using the `subplot` function.

* Recompute `x`, `y_sin` and `y_cos`.
* Set up a subplot grid of height 2 and width 1 and make the first subplot active; plot the sine curve
  there and title it `Sine`.
* Make the second subplot active; plot the cosine curve there and title it `Cosine`.
* Show the figure with `plt.show()`.

You can read much more about the `subplot` function in the
[documentation](https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.subplot.html).

In [ ]:
# Your code here

### Images

In a computer vision course, you will constantly use `matplotlib` to display and inspect images.
The `imshow` function displays a NumPy array as an image.

**Exercise 71.** * Import `load_sample_image` from `sklearn.datasets` and load the sample image `flower.jpg` into a
  variable named `img_array` (later exercises reuse this name).
* Print its shape — `(H, W, 3)` — and its dtype, which should be `uint8` with values in 0-255.
* Display it with `plt.imshow`, give it the title `Original image`, turn the axes off, and show the
  figure.

In [ ]:
# Your code here

**Exercise 72.** Visualize the individual color channels side by side.

* Create a figure with `plt.subplots(1, 3, figsize=(12, 4))`.
* Loop over the three channels; in each axis, `imshow` the corresponding channel of `img_array` as a
  2D array using the colormaps `Reds`, `Greens` and `Blues`, set the title to `Red`, `Green` or
  `Blue`, and turn the axis off.
* Give the whole figure the super-title `RGB Channels` and show it.

In [ ]:
# Your code here

**Exercise 73.** Since images are just NumPy arrays, you can manipulate them with all the array operations you already
know. Build an interactive widget that crops, flips and tints the image.

* Import `interact_manual`, `IntSlider`, `FloatSlider` and `Checkbox` from `ipywidgets`, and read
  `H, W` from the first two entries of `img_array.shape`.
* Write a function
  `manipulate_image(y_start=0, y_end=H, x_start=0, x_end=W, h_flip=False, v_flip=False, red=1.0, green=1.0, blue=1.0)`
  that:
  * crops the image with slicing on the first two axes;
  * flips it horizontally and/or vertically using a negative step slice (`::-1`) on the appropriate
    axis when the corresponding flag is set;
  * tints it by broadcasting the array `[red, green, blue]` across the channel axis, then clips the
    result to `[0, 255]` and casts it back to `np.uint8`;
  * draws the original and modified images side by side in a `(1, 2)` subplot grid with
    `figsize=(10, 4)`, titling the first `Original` and the second with the crop bounds, turning both
    axes off, and calling `plt.tight_layout()` before showing.
* Wire it up with `interact_manual`: `IntSlider`s for the four crop bounds (spanning the valid pixel
  ranges), `Checkbox`es for the two flips, and `FloatSlider`s for the three tint channels with
  `min=0`, `max=1.5`, `step=0.1`, `value=1.0`.

Then experiment with the sliders.

In [ ]:
# Your code here

## Conclusion

These exercises have covered a brief overview of Python, NumPy, and Matplotlib, which are the core
tools you will use throughout the course. The key takeaways to keep in mind as you start the assignments:

- **Vectorize your code.** Avoid Python loops over array elements; use NumPy operations instead. This
  will be the difference between code that runs in seconds vs. minutes.
- **Understand array shapes.** Most debugging in this course comes down to shape mismatches. Use
  `.shape` liberally and think in terms of `(N, H, W, C)` for image batches.
- **Use broadcasting.** Once it clicks, broadcasting lets you write concise, fast code without
  manually tiling or reshaping arrays.

You don't need to memorize every function so knowing how to look things up is just as important.

### Additional Resources

Check out plenty of learning resources here: https://numpy.org/learn/